<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?php
  echo $this->headTitle('Fly4sun');
  echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1');
  echo $this->headLink(array('rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath('/img/favicon.png')))
        ->prependStylesheet($this->basePath('/css/main.css'));
  echo $this->headScript()
        ->prependFile($this->basePath('/js/jquery-ui.js'))
        ->prependFile($this->basePath('/js/jquery.js'));
?>
<link href='http://fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>

<script>

  $(function() {
    $( ".datepicker" ).datepicker({
      minDate: 0,
      maxDate: "+7D"
    });

    var availableTags = [];

    $.get( "/supportedorigins", function( data ) {
      var locations = data._embedded.supportedorigins;
      for (i = 0; i < locations.length; i++ ) {
        availableTags.push(locations[i].cityName + " - " + locations[i].cityCode);
      }
    });

    $( "#place" ).autocomplete({
      source: availableTags
    });

    $( "#place" ).on( "autocompleteselect", function( event, ui ) {
      var code = ui.item.value.split("-")[1].trim();
      $("#originCity").val(code);
    } );

    $( "#submitButton" ).click( function(e){
      
      $("#logo").hide();
      $(".searchbox").addClass("sticky");

      e.preventDefault();

      $.ajax({
        url: '/api/search',
        type: 'get',
        dataType: 'json',
        data: $('form#searchForm').serialize(),
        success: function(data) {
          $.each(data, function(key,value) {
            console.log(value);
            $("#results").append(
              "<table class='results'><tr class='result-item'><td class='location'><span class='city'>" + value.destination.cityName + "</span><span class='airport'>" + value.destination.airportCode + "</span></td><td class='weather'><i class='wi wi-day-sunny'></i><i>" + value.weather.temperatureForecastDepartureDate + "</i></td><td class='dates'><i class='icon icon-departure'></i>" + value.schedule.departureTimeFormatted +"<br><i class='icon icon-land'></i>" + value.schedule.arrivalTimeFormatted + "</td><td class='time'>" + parseInt(parseInt(value.flightInformation.flightDurationMinutes)/60)+ " HOURS" + "</td><td class='price'><button class='button-primary'>" + value.price.totalPrice + "&nbsp;" + value.price.currency + "<span>Book Now</span></button></td></tr></table");
          })}
      });
    });
  });

  

  </script>

</head>

<body>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div class="container">
    <div class="row">
      <div class="one-half column" style="margin-top: 10%">
        <h1 id="logo">fly4sun.co</h1>
      </div>
    </div>
  </div>

  <div class="searchbox">
    <form id="searchForm">
      <div class="container">
        <div class="row">
          <div class="three columns">
            <label for="from">From</label>
            <input id="place" class="u-full-width" type="text" placeholder="e.g. Berlin">
            <input id="originCity" type="hidden" name="originCity" value="">
          </div>
          <div class="three columns">
            <label for="weather">Weather?</label>
            <select class="u-full-width">
            <option value="Option 1"><div class="icon icon-sun">&nbsp;</div>sunny</option>
            <option value="Option 2">windy</option>
            <option value="Option 3">snowy</option>
          </select>
          </div>
          <div class="two columns">
            <label for="from">Departure</label>
            <input class="u-full-width datepicker" type="text" placeholder="" id="fromDate">
          </div>
          <div class="two columns">
            <label for="weather">Arrival</label>
            <input class="u-full-width datepicker" type="text" placeholder="" id="ToDate">
          </div>
          <div class="two columns u-full-width">
            <button id="submitButton" class="button-primary">Search</button>
          </div>
        </div>
        </div>
      </div>
    </form>
  </div>

  <div id="results"class="container">
  </div>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
</body>
</html>